---


  - name: GATHER FACTS 
    hosts: lax
    connection: local
    gather_facts: no

    tasks:

      - name: GATHER FACTS
        junos_facts:

      - debug:
          var: ansible_facts

      - debug:
          var: ansible_net_version

      - name: GENERATE GROUPS BASED ON OS VERSION 
        group_by:
          key: target_{{ ansible_net_version }}


  - name: GATHER FACTS 
    hosts: target_15.1F4.15
    connection: local 
    gather_facts: no

    tasks:

      - debug:
          var: inventory_hostname
